module.exports = {
	'bitcoin': 'XBT',
	'bitcoins': 'XBT',
	'xbt': 'XBT',
	'ether': 'ETH',
	'ethereum': 'ETH',
	'eth': 'ETH',
	'dollar': 'USD',
	'dollars': 'USD',
	'usd': 'USD',
	'euro': 'EUR',
	'euros': 'EUR',
	'eur': 'EUR',
	'bitcoin cash': 'BCH',
	'bch': 'BCH',
	'dash': 'DASH',
	'ethereum classic': 'ETC',
	'etc': 'ETC',
	'litecoin': 'LTC',
	'ltc': 'LTC',
	'augur': 'REP',
	'rep': 'REP',
	'monero': 'XMR',
	'xmr': 'XMR',
	'ripple': 'XRP',
	'xrp': 'XRP',
	'zcash': 'ZEC',
	'zec': 'ZEC',
	'pound': 'GBP',
	'pounds': 'GBP',
	'gbp': 'GBP',
	'cad': 'CAD',
	'canadian dollar': 'CAD',
	'jpy': 'JPY',
	'japanese yen': 'JPY',
	'yen': 'YPY'
}
